name: CDKDeploy

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on: 
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Target Environment'
        required: true

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_environment }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "16"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ca-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
          role-duration-seconds: 900
          role-session-name: GH-${{ github.workflow }}-${{ github.job }}
      - name: Install dependencies
        run: npm install
      - run: |
          echo "$GITHUB_WORKSPACE/node_modules/.bin" >> $GITHUB_PATH
      - name: Synth stack
        run: cdk synth
      - name: Deploy stack
        run: cdk deploy --all --require-approval never
